In [1]:
import pandas as pd

from sklearn.datasets import load_digits

from sklearn.model_selection import GridSearchCV

from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [2]:
digits = load_digits()

In [6]:
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [7]:
digits.data.shape

(1797, 64)

In [8]:
model_params = {

    'svm': {

        'model': svm.SVC(gamma='auto'),

        'params': {

            'C':[1,10,20],

            'kernel':['rbf','linear']

        }

    },

    'random_forest': {

        'model': RandomForestClassifier(),

        'params': {

            'n_estimators':[10,20,50]

        }

    },

    'logistic_regression': {

        'model': LogisticRegression(
            solver='liblinear'
        ),

        'params': {

            'C':[1,5,10]

        }

    },

    'gaussian_nb': {

        'model': GaussianNB(),

        'params': {

        }

    },

    'multinomial_nb': {

        'model': MultinomialNB(),

        'params': {

        }

    },

    'decision_tree': {

        'model': DecisionTreeClassifier(),

        'params': {

            'criterion':['gini','entropy'],

            'max_depth':[5,10,15]

        }

    }

}

In [9]:
scores = []
for model_name, mp in model_params.items():

    clf = GridSearchCV(

        estimator=mp['model'],

        param_grid=mp['params'],

        cv=5,

        return_train_score=False

    )

    clf.fit(digits.data, digits.target)

    scores.append({

        'model': model_name,

        'best_score': clf.best_score_,

        'best_params': clf.best_params_

    })

In [11]:
df = pd.DataFrame(
    scores,
    columns=[
        'model',
        'best_score',
        'best_params'
    ]
)
df

                 model  best_score                                best_params
0                  svm    0.947697               {'C': 1, 'kernel': 'linear'}
1        random_forest    0.935463                       {'n_estimators': 50}
2  logistic_regression    0.922114                                   {'C': 1}
3          gaussian_nb    0.806928                                         {}
4       multinomial_nb    0.870350                                         {}
5        decision_tree    0.818601  {'criterion': 'entropy', 'max_depth': 10}

In [12]:
df.sort_values(
    by='best_score',
    ascending=False
)

                 model  best_score                                best_params
0                  svm    0.947697               {'C': 1, 'kernel': 'linear'}
1        random_forest    0.935463                       {'n_estimators': 50}
2  logistic_regression    0.922114                                   {'C': 1}
4       multinomial_nb    0.870350                                         {}
5        decision_tree    0.818601  {'criterion': 'entropy', 'max_depth': 10}
3          gaussian_nb    0.806928                                         {}